# Generated by Django 4.1.5 on 2023-02-13 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ("status",)},
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="Borrowing_id",
            new_name="borrowing_id",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="Money_to_pay",
            new_name="money_to_pay",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="Session_id",
            new_name="session_id",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="Session_url",
            new_name="session_url",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="Status",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="Type",
            new_name="type",
        ),
    ]
