# Generated by Django 4.1.5 on 2023-01-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=255)),
                ("Author", models.CharField(max_length=255)),
                (
                    "Cover",
                    models.CharField(
                        choices=[("HARD", "Hard"), ("SOFT", "Soft")], max_length=50
                    ),
                ),
                ("Inventory", models.PositiveIntegerField()),
                ("Daily_fee", models.DecimalField(decimal_places=4, max_digits=19)),
            ],
            options={
                "ordering": ("Title",),
            },
        ),
    ]
