# Generated by Django 4.1.5 on 2023-02-13 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ("title",)},
        ),
        migrations.RenameField(
            model_name="book",
            old_name="Author",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="Cover",
            new_name="cover",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="Daily_fee",
            new_name="daily_fee",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="Inventory",
            new_name="inventory",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="Title",
            new_name="title",
        ),
    ]
