# Generated by Django 4.1.5 on 2023-02-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_options_rename_author_book_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="daily_fee",
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
