# Generated by Django 4.1.5 on 2023-01-18 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Borrow_date", models.DateField()),
                ("Expected_return_date", models.DateField()),
                ("Actual_return_date", models.DateField(auto_now_add=True)),
                (
                    "Book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowings",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "ordering": ("Borrow_date",),
            },
        ),
    ]
