# Generated by Django 4.1.5 on 2023-01-30 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("borrowings", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ("borrow_date",)},
        ),
        migrations.RenameField(
            model_name="borrowing",
            old_name="Actual_return_date",
            new_name="actual_return_date",
        ),
        migrations.RenameField(
            model_name="borrowing",
            old_name="Book_id",
            new_name="book_id",
        ),
        migrations.RenameField(
            model_name="borrowing",
            old_name="Borrow_date",
            new_name="borrow_date",
        ),
        migrations.RenameField(
            model_name="borrowing",
            old_name="Expected_return_date",
            new_name="expected_return_date",
        ),
        migrations.RemoveField(
            model_name="borrowing",
            name="User_id",
        ),
        migrations.AddField(
            model_name="borrowing",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="borrowing",
            name="user_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowings",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
