# Generated by Django 4.1.5 on 2023-02-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0003_alter_borrowing_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="book_id",
            new_name="book",
        ),
        migrations.RenameField(
            model_name="borrowing",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="borrowing",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
